### ISSUE TITLE
session handling

### ISSUE THREAD

**Issue by Enovotny** [HydrologicEngineeringCenter/cwms-python#12]
I want the repo to default to CWBI-prod.  Outside users would not have to set api_session.  They would be able to retrieve data by simply doing the following

from CWMS import CwmsTs
ts_data = CwmsTs.retrieve_ts_json(tsid, 'MVP')

or

import CWMS
ts_data = CWMS.CwmsTs.retrieve_ts_json(tsid,'MVP')

Then have the ability to change api_session if connecting to a different URL. would like to only have to update api_session and then it transfers to all classes instead of having to run

cwsm_ts = CwmsTs(api_session) 
cwms_loc = CwmsLoc(api_session)

for each class, but I don't know if that is possible.

**Comment by adamkorynta** [comment]
I don't like the idea of hiding the URL from the user so I think parameterizing the API constructors is still a good idea. To avoid needing the user to type out the URL, factory methods can help:

```
import cwms

cwms_prod_session = cwms.cwbi_prod_session() #optional apikey
prod_ts = cwms.TimeSeries(cwms_prod_session)

cwms_test_session = cwms.cwbi_test_session() #optional apikey
test_ts = cwms.TimeSeries(cwms_test_session)

district_session = cwms.district_session("https://spk.district.url/spk-data/") #optional apikey
district_ts = cwms.TimeSeries(district_session)
```

**Comment by Enovotny** [comment]
I am thinking about the case of the public (i.e. other government agencies, researchers, consultants) who want to use cwms-python to access our data.  they shouldn't have to know what cwbi-production is or what url to use.  They just need to know they are collection data from USACE.  In a couple years we will just have cwbi-prod and cwbi-test maybe a cwbi-dev.  most users both internal and external will only be connecting to cwbi-prod.  The other 2 will only be used for development.  The ability to connect to district servers is only short term.  I feel the public should be able in one line of code to access time series data.  I would like the same usability for the public as the USGS dataretrieval-python.

**Comment by adamkorynta** [comment]
What do you think about adding factory methods for the default URL in the init? 

Example: https://github.com/HydrologicEngineeringCenter/cwms-python/pull/14
