### ISSUE TITLE
update all class names/module names

### ISSUE THREAD

**Issue by Enovotny** [HydrologicEngineeringCenter/cwms-python#13]
update module folder name from CWMS to cwms to follow python naming conventions.

update class names to snake formatting.  i.e. update CwmsTs to cwms_ts or just ts.

when using it could be 

import cwms
ts_data = cwms.ts.retrieve_ts_json()

or

from cwms import ts
ts_data = ts.retrieve_ts_json()

**Comment by adamkorynta** [comment]
I think we should adhere to the PEP 8 style guides as much as we can. 

The camel case class names follow that convention now.
The module and package names being all lower-case follows PEP 8.

I don't like shortening words, so I wouldn't go with `ts` or `TS` and prefer the full `TimeSeries`, but I can see ditching the `Cwms` prefix.

so
```
import cwms
cwms.TimeSeries(session).retrieve_ts_json()
```

**Comment by devinrei** [comment]
I agree with Adam that the cwms prefix is unnecessary and that time series should be spelled out for its variable name. In regards to the snake case vs camel case I don't think it matters as long as there's consistency amongst all the files.

**Comment by zchapman-gei** [comment]
I agree that PEP 8 should be the standard. https://peps.python.org/pep-0008/#naming-conventions
