### ISSUE TITLE
Method to convert back to cwms data type?

### ISSUE THREAD

**Issue by msweier** [HydrologicEngineeringCenter/cwms-python#51]
Is there a way to get back to the cwms data type from a dataframe or json type? This would be useful when writing modular functions (e.g. merge) that input one or more cwms data types and will return cwms data types. This would keep the metadata along with the dataframes.

**Comment by Enovotny** [comment]
I am not sure the use case for this.  The cwms data type isn't supposed to be like a timeseries container.  It is just a way to get both a json and dataframe from CDA then the user can pick which one to use.  cwms-python doesn't accept the cwms data type for writing.  If I were to merge 3 time series together I would use a dataframe then pandas functions to merge them together. Once merged you wouldn't need or want the meta data from all 3 time series.  If you were then to write the data back to the database you would would only need the information for the time series that you are writing to.  the meta data from the original datasets are no longer relevant.  In general don't think I like the idea of creating functions to do computation with the cwms data type.  The purpose would be to use existing tools in pandas or other python libraries to complete any of those functions.

**Comment by msweier** [comment]
Once I started using it, I began to see how this would help clean up the scripting. I understand we need to write back to w/ JSON and not making a case for that or do any math with a cwms data type. I'm doing all the math with pandas dataframes, but converting back to a cwms datatype allows for consistent methods to access the metadata if a function gets a cwms data type or json.

Here my case for having a method to convert back:
The units, office, and most of the timeseries won't change (e.g. location, parameter etc....) when performing math on timeseries. Your target metadata will be pretty similar, so it's nice to have easy access to it.  You can carry the metadata around in a JSON object, but accessing the metadata from JSON is a different syntax than a cwms object. Also converting JSON back to a dataframe is a different method than the cwms object to dataframe. So any scripting functions need to figure out if you are dealing w/ a JSON object or cwms object. Because of the [payload write limit in CDA](https://github.com/USACE/cwms-data-api/issues/632) (which looks like it will be improved), I've got a function to write large timeseries to CDA which needs to break down a JSON object or a cwms object to a dataframe, make small JSON chunks and then write it.

I suppose one could just convert things to json from the get go and just assume all inputs to your functions are JSON, but the cwms data type seemed kinda cool.

**Comment by msweier** [comment]
Spoke with @Enovotny and saw the light.
