### ISSUE TITLE
Handle timeseries values outside data extents

### ISSUE THREAD

**Issue by msweier** [HydrologicEngineeringCenter/cwms-python#52]
Currently CDA will generate null values for times outside timeseries limits. There will be a [trim flag in a new release.](https://github.com/USACE/cwms-data-api/issues/629). Cwms-python may need changes to handle the trim flag.

**Comment by Enovotny** [comment]
The new CDA version has this now.  It defaults to Trim.  The trim parameter will need to be added if people don't want it trimmed.
