### ISSUE TITLE
Update to work with CDA to handle large data posts

### ISSUE THREAD

**Issue by msweier** [HydrologicEngineeringCenter/cwms-python#53]
CDA currently has a limit of [1 MB for writing, but will this will be raised soon](https://github.com/USACE/cwms-data-api/issues/632). Depending on how small the upper limit ends up being, cwms-python may need to check the payload size before writing and if payload exceeds the limit, break the payload up into smaller chunks to write. Some timeseries period of record data I was trying to write was 10 to 20 MB.

**Comment by Enovotny** [comment]
@msweier can you test with newest version of CDA and see if we need to do anything on the cwms-python side.

**Comment by msweier** [comment]
I just saved a 15 MB combined timeseries, so I think it is all set.
