### ISSUE TITLE
Feature: Change inputs to store_stadard_text to take id, standard_text, and office_id

### ISSUE THREAD

**Issue by msweier** [HydrologicEngineeringCenter/cwms-python#69]
Changing inputs to store_standard_text to take text_id, standard_text, and office_id and building the data json dictionary would make it a little easier to use.

e.g. 

```   
def store_standard_text(text_id: str, standard_text: str, 
                        office_id: str, fail_if_exists: bool = False) -> None:
     data = {
                "id": {
                    "office-id": f"{office_id}",
                    "id": f"{text_id}"
                },
                "standard-text": f"{standard_text}"
                }
    if text_id is None:
        raise ValueError("Cannot store a standard text without a text id")
    
    if standard_text is None:
        raise ValueError("Cannot store a standard text without a standard_text message")
    
    if office_id is None:
        raise ValueError("Cannot store a standard text without an office_id")```

**Comment by Enovotny** [comment]
I think to keep things consistent we could create a standard_text_to_json function that would input those parameters and output the json that could then go into the store function.  Have you tested if this can store multiple standard_texts or if it only stores a single one @adamkorynta do you know the answer to that. If it can accept multiple standard texts similar to what is given from the /cwms-data/standard-text-id get endpoint.  My guess is no.   

{
  "values": [
    {
      "id": {
        "office-id": "CWMS",
        "id": "A"
      },
      "standard-text": "NO RECORD"
    },
    {
      "id": {
        "office-id": "CWMS",
        "id": "B"
      },
      "standard-text": "CHANNEL DRY"
    }
]
}

**Comment by adamkorynta** [comment]
The endpoint only supports storing a single id per request (similar to pretty much all CDA endpoints).
